version: "3.9"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    container_name: frontend
    networks: 
      - mynetwork

  backend:
    build: ./backend
    depends_on: 
      - db
    ports: 
      - "8000:8000"
    container_name: backend-docker
    restart: always
    networks: 
      - mynetwork

  db:
    container_name: database-docker
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PSW}
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

networks:
  mynetwork:
