# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.2.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.0.tgz";
        sha512 = "qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==";
      };
    };
    "@babel/code-frame-7.18.6" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.18.6.tgz";
        sha512 = "TDCmlK5eOvH+eH7cdAFlNXeVJqWIQ7gW9tY1GJIpUtFb6CmjVyq2VM3u71bOyR8CRihcCgMUYoDNyLXao3+70Q==";
      };
    };
    "@babel/compat-data-7.20.5" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.20.5.tgz";
        sha512 = "KZXo2t10+/jxmkhNXc7pZTqRvSOIvVv/+lJwHS+B2rErwOyjuVRh60yVpb7liQ1U5t7lLJ1bz+t8tSypUZdm0g==";
      };
    };
    "@babel/core-7.20.5" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.20.5.tgz";
        sha512 = "UdOWmk4pNWTm/4DlPUl/Pt4Gz4rcEMb7CY0Y3eJl5Yz1vI8ZJGmHWaVE55LoxRjdpx0z259GE9U5STA9atUinQ==";
      };
    };
    "@babel/generator-7.20.5" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.20.5.tgz";
        sha512 = "jl7JY2Ykn9S0yj4DQP82sYvPU+T3g0HFcWTqDLqiuA9tGRNIj9VfbtXGAYTTkyNEnQk1jkMGOdYka8aG/lulCA==";
      };
    };
    "@babel/helper-compilation-targets-7.20.0" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.20.0.tgz";
        sha512 = "0jp//vDGp9e8hZzBc6N/KwA5ZK3Wsm/pfm4CrY7vzegkVxc65SgSn6wYOnwHe9Js9HRQ1YTCKLGPzDtaS3RoLQ==";
      };
    };
    "@babel/helper-environment-visitor-7.18.9" = {
      name = "_at_babel_slash_helper-environment-visitor";
      packageName = "@babel/helper-environment-visitor";
      version = "7.18.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-environment-visitor/-/helper-environment-visitor-7.18.9.tgz";
        sha512 = "3r/aACDJ3fhQ/EVgFy0hpj8oHyHpQc+LPtJoY9SzTThAsStm4Ptegq92vqKoE3vD706ZVFWITnMnxucw+S9Ipg==";
      };
    };
    "@babel/helper-function-name-7.19.0" = {
      name = "_at_babel_slash_helper-function-name";
      packageName = "@babel/helper-function-name";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-function-name/-/helper-function-name-7.19.0.tgz";
        sha512 = "WAwHBINyrpqywkUH0nTnNgI5ina5TFn85HKS0pbPDfxFfhyR/aNQEn4hGi1P1JyT//I0t4OgXUlofzWILRvS5w==";
      };
    };
    "@babel/helper-hoist-variables-7.18.6" = {
      name = "_at_babel_slash_helper-hoist-variables";
      packageName = "@babel/helper-hoist-variables";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.18.6.tgz";
        sha512 = "UlJQPkFqFULIcyW5sbzgbkxn2FKRgwWiRexcuaR8RNJRy8+LLveqPjwZV/bwrLZCN0eUHD/x8D0heK1ozuoo6Q==";
      };
    };
    "@babel/helper-module-imports-7.18.6" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.18.6.tgz";
        sha512 = "0NFvs3VkuSYbFi1x2Vd6tKrywq+z/cLeYC/RJNFrIX/30Bf5aiGYbtvGXolEktzJH8o5E5KJ3tT+nkxuuZFVlA==";
      };
    };
    "@babel/helper-module-transforms-7.20.2" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.20.2.tgz";
        sha512 = "zvBKyJXRbmK07XhMuujYoJ48B5yvvmM6+wcpv6Ivj4Yg6qO7NOZOSnvZN9CRl1zz1Z4cKf8YejmCMh8clOoOeA==";
      };
    };
    "@babel/helper-plugin-utils-7.20.2" = {
      name = "_at_babel_slash_helper-plugin-utils";
      packageName = "@babel/helper-plugin-utils";
      version = "7.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-plugin-utils/-/helper-plugin-utils-7.20.2.tgz";
        sha512 = "8RvlJG2mj4huQ4pZ+rU9lqKi9ZKiRmuvGuM2HlWmkmgOhbs6zEAw6IEiJ5cQqGbDzGZOhwuOQNtZMi/ENLjZoQ==";
      };
    };
    "@babel/helper-simple-access-7.20.2" = {
      name = "_at_babel_slash_helper-simple-access";
      packageName = "@babel/helper-simple-access";
      version = "7.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-simple-access/-/helper-simple-access-7.20.2.tgz";
        sha512 = "+0woI/WPq59IrqDYbVGfshjT5Dmk/nnbdpcF8SnMhhXObpTq2KNBdLFRFrkVdbDOyUmHBCxzm5FHV1rACIkIbA==";
      };
    };
    "@babel/helper-split-export-declaration-7.18.6" = {
      name = "_at_babel_slash_helper-split-export-declaration";
      packageName = "@babel/helper-split-export-declaration";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.18.6.tgz";
        sha512 = "bde1etTx6ZyTmobl9LLMMQsaizFVZrquTEHOqKeQESMKo4PlObf+8+JA25ZsIpZhT/WEd39+vOdLXAFG/nELpA==";
      };
    };
    "@babel/helper-string-parser-7.19.4" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.19.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.19.4.tgz";
        sha512 = "nHtDoQcuqFmwYNYPz3Rah5ph2p8PFeFCsZk9A/48dPc/rGocJ5J3hAAZ7pb76VWX3fZKu+uEr/FhH5jLx7umrw==";
      };
    };
    "@babel/helper-validator-identifier-7.19.1" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.19.1.tgz";
        sha512 = "awrNfaMtnHUr653GgGEs++LlAvW6w+DcPrOliSMXWCKo597CwL5Acf/wWdNkf/tfEQE3mjkeD1YOVZOUV/od1w==";
      };
    };
    "@babel/helper-validator-option-7.18.6" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.18.6.tgz";
        sha512 = "XO7gESt5ouv/LRJdrVjkShckw6STTaB7l9BrpBaAHDeF5YZT+01PCwmR0SJHnkW6i8OwW/EVWRShfi4j2x+KQw==";
      };
    };
    "@babel/helpers-7.20.6" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.20.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.20.6.tgz";
        sha512 = "Pf/OjgfgFRW5bApskEz5pvidpim7tEDPlFtKcNRXWmfHGn9IEI2W2flqRQXTFb7gIPTyK++N6rVHuwKut4XK6w==";
      };
    };
    "@babel/highlight-7.18.6" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.18.6.tgz";
        sha512 = "u7stbOuYjaPezCuLj29hNW1v64M2Md2qupEKP1fHc7WdOA3DgLh37suiSrZYY7haUB7iBeQZ9P1uiRF359do3g==";
      };
    };
    "@babel/parser-7.20.5" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.20.5.tgz";
        sha512 = "r27t/cy/m9uKLXQNWWebeCUHgnAZq0CpG1OwKRxzJMP1vpSU4bSIK2hq+/cp0bQxetkXx38n09rNu8jVkcK/zA==";
      };
    };
    "@babel/plugin-syntax-jsx-7.18.6" = {
      name = "_at_babel_slash_plugin-syntax-jsx";
      packageName = "@babel/plugin-syntax-jsx";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-syntax-jsx/-/plugin-syntax-jsx-7.18.6.tgz";
        sha512 = "6mmljtAedFGTWu2p/8WIORGwy+61PLgOMPOdazc7YoJ9ZCWUyFy3A6CpPkRKLKD1ToAesxX8KGEViAiLo9N+7Q==";
      };
    };
    "@babel/runtime-7.20.6" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.20.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.20.6.tgz";
        sha512 = "Q+8MqP7TiHMWzSfwiJwXCjyf4GYA4Dgw3emg/7xmwsdLJOZUp+nMqcOwOzzYheuM1rhDu8FSj2l0aoMygEuXuA==";
      };
    };
    "@babel/template-7.18.10" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.18.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.18.10.tgz";
        sha512 = "TI+rCtooWHr3QJ27kJxfjutghu44DLnasDMwpDqCXVTal9RLp3RSYNh4NdBrRP2cQAoG9A8juOQl6P6oZG4JxA==";
      };
    };
    "@babel/traverse-7.20.5" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.20.5.tgz";
        sha512 = "WM5ZNN3JITQIq9tFZaw1ojLU3WgWdtkxnhM1AegMS+PvHjkM5IXjmYEGY7yukz5XS4sJyEf2VzWjI8uAavhxBQ==";
      };
    };
    "@babel/types-7.20.5" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.20.5.tgz";
        sha512 = "c9fst/h2/dcF7H+MJKZ2T0KjEQ8hY/BNnDk/H3XY8C4Aw/eWQXWn/lWntHF9ooUBnGmEvbfGrTgLWc+um0YDUg==";
      };
    };
    "@emotion/babel-plugin-11.10.5" = {
      name = "_at_emotion_slash_babel-plugin";
      packageName = "@emotion/babel-plugin";
      version = "11.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/babel-plugin/-/babel-plugin-11.10.5.tgz";
        sha512 = "xE7/hyLHJac7D2Ve9dKroBBZqBT7WuPQmWcq7HSGb84sUuP4mlOWoB8dvVfD9yk5DHkU1m6RW7xSoDtnQHNQeA==";
      };
    };
    "@emotion/cache-11.10.5" = {
      name = "_at_emotion_slash_cache";
      packageName = "@emotion/cache";
      version = "11.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/cache/-/cache-11.10.5.tgz";
        sha512 = "dGYHWyzTdmK+f2+EnIGBpkz1lKc4Zbj2KHd4cX3Wi8/OWr5pKslNjc3yABKH4adRGCvSX4VDC0i04mrrq0aiRA==";
      };
    };
    "@emotion/hash-0.9.0" = {
      name = "_at_emotion_slash_hash";
      packageName = "@emotion/hash";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/hash/-/hash-0.9.0.tgz";
        sha512 = "14FtKiHhy2QoPIzdTcvh//8OyBlknNs2nXRwIhG904opCby3l+9Xaf/wuPvICBF0rc1ZCNBd3nKe9cd2mecVkQ==";
      };
    };
    "@emotion/is-prop-valid-0.8.8" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "0.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-0.8.8.tgz";
        sha512 = "u5WtneEAr5IDG2Wv65yhunPSMLIpuKsbuOktRojfrEiEvRyC85LgPMZI63cr7NUqT8ZIGdSVg8ZKGxIug4lXcA==";
      };
    };
    "@emotion/is-prop-valid-1.2.0" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-1.2.0.tgz";
        sha512 = "3aDpDprjM0AwaxGE09bOPkNxHpBd+kA6jty3RnaEXdweX1DF1U3VQpPYb0g1IStAuK7SVQ1cy+bNBBKp4W3Fjg==";
      };
    };
    "@emotion/memoize-0.7.4" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz";
        sha512 = "Ja/Vfqe3HpuzRsG1oBtWTHk2PGZ7GR+2Vz5iYGelAw8dx32K0y7PjVuxK6z1nMpZOqAFsRUPCkK1YjJ56qJlgw==";
      };
    };
    "@emotion/memoize-0.8.0" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.8.0.tgz";
        sha512 = "G/YwXTkv7Den9mXDO7AhLWkE3q+I92B+VqAE+dYG4NGPaHZGvt3G8Q0p9vmE+sq7rTGphUbAvmQ9YpbfMQGGlA==";
      };
    };
    "@emotion/react-11.10.5" = {
      name = "_at_emotion_slash_react";
      packageName = "@emotion/react";
      version = "11.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/react/-/react-11.10.5.tgz";
        sha512 = "TZs6235tCJ/7iF6/rvTaOH4oxQg2gMAcdHemjwLKIjKz4rRuYe1HJ2TQJKnAcRAfOUDdU8XoDadCe1rl72iv8A==";
      };
    };
    "@emotion/serialize-1.1.1" = {
      name = "_at_emotion_slash_serialize";
      packageName = "@emotion/serialize";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/serialize/-/serialize-1.1.1.tgz";
        sha512 = "Zl/0LFggN7+L1liljxXdsVSVlg6E/Z/olVWpfxUTxOAmi8NU7YoeWeLfi1RmnB2TATHoaWwIBRoL+FvAJiTUQA==";
      };
    };
    "@emotion/sheet-1.2.1" = {
      name = "_at_emotion_slash_sheet";
      packageName = "@emotion/sheet";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/sheet/-/sheet-1.2.1.tgz";
        sha512 = "zxRBwl93sHMsOj4zs+OslQKg/uhF38MB+OMKoCrVuS0nyTkqnau+BM3WGEoOptg9Oz45T/aIGs1qbVAsEFo3nA==";
      };
    };
    "@emotion/styled-11.10.5" = {
      name = "_at_emotion_slash_styled";
      packageName = "@emotion/styled";
      version = "11.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/styled/-/styled-11.10.5.tgz";
        sha512 = "8EP6dD7dMkdku2foLoruPCNkRevzdcBaY6q0l0OsbyJK+x8D9HWjX27ARiSIKNF634hY9Zdoedh8bJCiva8yZw==";
      };
    };
    "@emotion/unitless-0.8.0" = {
      name = "_at_emotion_slash_unitless";
      packageName = "@emotion/unitless";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/unitless/-/unitless-0.8.0.tgz";
        sha512 = "VINS5vEYAscRl2ZUDiT3uMPlrFQupiKgHz5AA4bCH1miKBg4qtwkim1qPmJj/4WG6TreYMY111rEFsjupcOKHw==";
      };
    };
    "@emotion/use-insertion-effect-with-fallbacks-1.0.0" = {
      name = "_at_emotion_slash_use-insertion-effect-with-fallbacks";
      packageName = "@emotion/use-insertion-effect-with-fallbacks";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/use-insertion-effect-with-fallbacks/-/use-insertion-effect-with-fallbacks-1.0.0.tgz";
        sha512 = "1eEgUGmkaljiBnRMTdksDV1W4kUnmwgp7X9G8B++9GYwl1lUdqSndSriIrTJ0N7LQaoauY9JJ2yhiOYK5+NI4A==";
      };
    };
    "@emotion/utils-1.2.0" = {
      name = "_at_emotion_slash_utils";
      packageName = "@emotion/utils";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/utils/-/utils-1.2.0.tgz";
        sha512 = "sn3WH53Kzpw8oQ5mgMmIzzyAaH2ZqFEbozVVBSYp538E06OSE6ytOp7pRAjNQR+Q/orwqdQYJSe2m3hCOeznkw==";
      };
    };
    "@emotion/weak-memoize-0.3.0" = {
      name = "_at_emotion_slash_weak-memoize";
      packageName = "@emotion/weak-memoize";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/weak-memoize/-/weak-memoize-0.3.0.tgz";
        sha512 = "AHPmaAx+RYfZz0eYu6Gviiagpmiyw98ySSlQvCUhVGDRtDFe4DBS0x1bSjdF3gqUDYOczB+yYvBTtEylYSdRhg==";
      };
    };
    "@floating-ui/core-1.0.4" = {
      name = "_at_floating-ui_slash_core";
      packageName = "@floating-ui/core";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/core/-/core-1.0.4.tgz";
        sha512 = "FPFLbg2b06MIw1dqk2SOEMAMX3xlrreGjcui5OTxfBDtaKTmh0kioOVjT8gcfl58juawL/yF+S+gnq8aUYQx/Q==";
      };
    };
    "@floating-ui/dom-1.0.9" = {
      name = "_at_floating-ui_slash_dom";
      packageName = "@floating-ui/dom";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/dom/-/dom-1.0.9.tgz";
        sha512 = "nF9P6/BoARdt+h+CdUW3td4EUVngeDONCGuzRgnZveRZiJETx63cxhinE0JaPPC2tbcdTY9IGZocS5/7ag3xRg==";
      };
    };
    "@floating-ui/react-dom-1.0.1" = {
      name = "_at_floating-ui_slash_react-dom";
      packageName = "@floating-ui/react-dom";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/react-dom/-/react-dom-1.0.1.tgz";
        sha512 = "UW0t1Gi8ikbDRr8cQPVcqIDMBwUEENe5V4wlHWdrJ5egFnRQFBV9JirauTBFI6S8sM1qFUC1i+qa3g87E6CLTw==";
      };
    };
    "@floating-ui/react-dom-interactions-0.8.1" = {
      name = "_at_floating-ui_slash_react-dom-interactions";
      packageName = "@floating-ui/react-dom-interactions";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/react-dom-interactions/-/react-dom-interactions-0.8.1.tgz";
        sha512 = "Cd1rk2WE4lrJhPkLiYgTLK8sxsdFn/b8WV7Mncw2wwOt8zgMstwA7EHTQutHUDOA7qI+zCYt6LqWIMkazEPcBw==";
      };
    };
    "@jridgewell/gen-mapping-0.1.1" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.1.1.tgz";
        sha512 = "sQXCasFk+U8lWYEe66WxRDOE9PjVz4vSM51fTu3Hw+ClTpUSQb718772vH3pyS5pShp6lvQM7SxgIDXXXmOX7w==";
      };
    };
    "@jridgewell/gen-mapping-0.3.2" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.2.tgz";
        sha512 = "mh65xKQAzI6iBcFzwv28KVWSmCkdRBWoOh+bYQGW3+6OZvbbN3TqMGo5hqYxQniRcH9F2VZIoJCm4pa3BPDK/A==";
      };
    };
    "@jridgewell/resolve-uri-3.1.0" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.0.tgz";
        sha512 = "F2msla3tad+Mfht5cJq7LSXcdudKTWCVYUgw6pLFOOHSTtZlj6SWNYAp+AhuqLmWdBO2X5hPrLcu8cVP8fy28w==";
      };
    };
    "@jridgewell/set-array-1.1.2" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.1.2.tgz";
        sha512 = "xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.14" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.14.tgz";
        sha512 = "XPSJHWmi394fuUuzDnGz1wiKqWfo1yXecHQMRf2l6hztTO+nPru658AyDngaBe7isIxEkRsPR3FZh+s7iVa4Uw==";
      };
    };
    "@jridgewell/trace-mapping-0.3.17" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.17.tgz";
        sha512 = "MCNzAp77qzKca9+W/+I0+sEpaUnZoeasnghNeVc41VZCEKaCH73Vq3BZZ/SzWIgrqE4H4ceI+p+b6C0mHf9T4g==";
      };
    };
    "@material-tailwind/react-1.2.4" = {
      name = "_at_material-tailwind_slash_react";
      packageName = "@material-tailwind/react";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material-tailwind/react/-/react-1.2.4.tgz";
        sha512 = "cDmdOEyg/uekLtUtjxPzgvqfkZdyZUDR2gpIIWd6ZSpfPprSHHBvzr92TtIx59+NlX3l3Fh+6702qwGmdRvyqA==";
      };
    };
    "@motionone/animation-10.15.1" = {
      name = "_at_motionone_slash_animation";
      packageName = "@motionone/animation";
      version = "10.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/animation/-/animation-10.15.1.tgz";
        sha512 = "mZcJxLjHor+bhcPuIFErMDNyrdb2vJur8lSfMCsuCB4UyV8ILZLvK+t+pg56erv8ud9xQGK/1OGPt10agPrCyQ==";
      };
    };
    "@motionone/dom-10.12.0" = {
      name = "_at_motionone_slash_dom";
      packageName = "@motionone/dom";
      version = "10.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/dom/-/dom-10.12.0.tgz";
        sha512 = "UdPTtLMAktHiqV0atOczNYyDd/d8Cf5fFsd1tua03PqTwwCe/6lwhLSQ8a7TbnQ5SN0gm44N1slBfj+ORIhrqw==";
      };
    };
    "@motionone/easing-10.15.1" = {
      name = "_at_motionone_slash_easing";
      packageName = "@motionone/easing";
      version = "10.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/easing/-/easing-10.15.1.tgz";
        sha512 = "6hIHBSV+ZVehf9dcKZLT7p5PEKHGhDwky2k8RKkmOvUoYP3S+dXsKupyZpqx5apjd9f+php4vXk4LuS+ADsrWw==";
      };
    };
    "@motionone/generators-10.15.1" = {
      name = "_at_motionone_slash_generators";
      packageName = "@motionone/generators";
      version = "10.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/generators/-/generators-10.15.1.tgz";
        sha512 = "67HLsvHJbw6cIbLA/o+gsm7h+6D4Sn7AUrB/GPxvujse1cGZ38F5H7DzoH7PhX+sjvtDnt2IhFYF2Zp1QTMKWQ==";
      };
    };
    "@motionone/types-10.15.1" = {
      name = "_at_motionone_slash_types";
      packageName = "@motionone/types";
      version = "10.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/types/-/types-10.15.1.tgz";
        sha512 = "iIUd/EgUsRZGrvW0jqdst8st7zKTzS9EsKkP+6c6n4MPZoQHwiHuVtTQLD6Kp0bsBLhNzKIBlHXponn/SDT4hA==";
      };
    };
    "@motionone/utils-10.15.1" = {
      name = "_at_motionone_slash_utils";
      packageName = "@motionone/utils";
      version = "10.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/utils/-/utils-10.15.1.tgz";
        sha512 = "p0YncgU+iklvYr/Dq4NobTRdAPv9PveRDUXabPEeOjBLSO/1FNB2phNTZxOxpi1/GZwYpAoECEa0Wam+nsmhSw==";
      };
    };
    "@mui/base-5.0.0-alpha.107" = {
      name = "_at_mui_slash_base";
      packageName = "@mui/base";
      version = "5.0.0-alpha.107";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/base/-/base-5.0.0-alpha.107.tgz";
        sha512 = "HX/BD8CSe+Y/dpbZ5aKJScJhKQ/Hw6du2yd68Upv2cO67bwixyZ64h3aNcdDu7RQzI7nrZQm0JykffP1Orgq0g==";
      };
    };
    "@mui/base-5.0.0-alpha.109" = {
      name = "_at_mui_slash_base";
      packageName = "@mui/base";
      version = "5.0.0-alpha.109";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/base/-/base-5.0.0-alpha.109.tgz";
        sha512 = "UQxoONPI3ntzxcD/cbFHl+Lp2xsVj6HpKmU9QhUZ2kZ2K2yej2QJyU1gnADoWl/Hu94VrvwSSRnjTjR3HvXO/g==";
      };
    };
    "@mui/core-downloads-tracker-5.10.17" = {
      name = "_at_mui_slash_core-downloads-tracker";
      packageName = "@mui/core-downloads-tracker";
      version = "5.10.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/core-downloads-tracker/-/core-downloads-tracker-5.10.17.tgz";
        sha512 = "iNwUuMA30nrN0tiEkeD3zaczv7Tk2jlZIDbXRnijAsYXkZtl/xEzQsVRIPYRDuyEz6D18vQJhV8h7gPUXEubTg==";
      };
    };
    "@mui/icons-material-5.10.16" = {
      name = "_at_mui_slash_icons-material";
      packageName = "@mui/icons-material";
      version = "5.10.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/icons-material/-/icons-material-5.10.16.tgz";
        sha512 = "jjCc0IF6iyLiucQCu5igg3fOscSqbbvRCmyRxXgzOcLR56B0sg2L8o+ZfJ0dAg59+wvgtXaxvjze/mJg0B4iWA==";
      };
    };
    "@mui/lab-5.0.0-alpha.109" = {
      name = "_at_mui_slash_lab";
      packageName = "@mui/lab";
      version = "5.0.0-alpha.109";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/lab/-/lab-5.0.0-alpha.109.tgz";
        sha512 = "9ZyzM4AHA1qWh48ZcvqxqwWRH1CzBhQuP9VYP2eEprEjEeraiuvvsZILCNhCemc9WWN04GJh8UiD1FeCaU4kWg==";
      };
    };
    "@mui/material-5.10.17" = {
      name = "_at_mui_slash_material";
      packageName = "@mui/material";
      version = "5.10.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/material/-/material-5.10.17.tgz";
        sha512 = "Kuqgv1qI5HXnc/Xu426xhCGYBSKzplb+xFNLitbnIb92Qx8jmcpfNpFlDJa2kD2H6qP66rr/m4c/zMUfGX/xBQ==";
      };
    };
    "@mui/private-theming-5.10.16" = {
      name = "_at_mui_slash_private-theming";
      packageName = "@mui/private-theming";
      version = "5.10.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/private-theming/-/private-theming-5.10.16.tgz";
        sha512 = "0MArkJaOHRCKqL/GWjngGZmyOeRz+uxffhx82bKcewr8swqV7xx7EFP02pk0L/gLdfcvYdqwH4YTVjG/+TaKrg==";
      };
    };
    "@mui/styled-engine-5.10.16" = {
      name = "_at_mui_slash_styled-engine";
      packageName = "@mui/styled-engine";
      version = "5.10.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/styled-engine/-/styled-engine-5.10.16.tgz";
        sha512 = "ZMSjXvtiGwGDKqrSlXhpxK2voUaF2/lpC/pSTfFmZvKH9j9a9h1/iwo3ybgjFVYGgbfNeW4h0xEchiRohu9xsw==";
      };
    };
    "@mui/system-5.10.17" = {
      name = "_at_mui_slash_system";
      packageName = "@mui/system";
      version = "5.10.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/system/-/system-5.10.17.tgz";
        sha512 = "UYzAOSK7uxkMsUssqrIUW3lnOuQpU8vqh4hLwfSw+GYAnQo3qjK4m4NhlDx+pFpsjjiGnr3K+vrSH+aIAMbcLg==";
      };
    };
    "@mui/types-7.2.2" = {
      name = "_at_mui_slash_types";
      packageName = "@mui/types";
      version = "7.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/types/-/types-7.2.2.tgz";
        sha512 = "siex8cZDtWeC916cXOoUOnEQQejuMYmHtc4hM6VkKVYaBICz3VIiqyiAomRboTQHt2jchxQ5Q5ATlbcDekTxDA==";
      };
    };
    "@mui/utils-5.10.16" = {
      name = "_at_mui_slash_utils";
      packageName = "@mui/utils";
      version = "5.10.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/utils/-/utils-5.10.16.tgz";
        sha512 = "3MB/SGsgiiu9Z55CFmAfiONUoR7AAue/H4F6w3mc2LnhFQCsoVvXhioDPcsiRpUMIQr34jDPzGXdCuqWooPCXQ==";
      };
    };
    "@popperjs/core-2.11.6" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.11.6.tgz";
        sha512 = "50/17A98tWUfQ176raKiOGXuYpLyyVMkxxG6oylzL3BPOlA6ADGdK7EYunSa4I064xerltq9TGXs8HmOk5E+vw==";
      };
    };
    "@remix-run/router-1.0.5" = {
      name = "_at_remix-run_slash_router";
      packageName = "@remix-run/router";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@remix-run/router/-/router-1.0.5.tgz";
        sha512 = "my0Mycd+jruq/1lQuO5LBB6WTlL/e8DTCYWp44DfMTDcXz8DcTlgF0ISaLsGewt+ctHN+yA8xMq3q/N7uWJPug==";
      };
    };
    "@types/history-4.7.11" = {
      name = "_at_types_slash_history";
      packageName = "@types/history";
      version = "4.7.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/history/-/history-4.7.11.tgz";
        sha512 = "qjDJRrmvBMiTx+jyLxvLfJU7UznFuokDv4f3WRuriHKERccVpFU+8XMQUAbDzoiJCsmexxRExQeMwwCdamSKDA==";
      };
    };
    "@types/parse-json-4.0.0" = {
      name = "_at_types_slash_parse-json";
      packageName = "@types/parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse-json/-/parse-json-4.0.0.tgz";
        sha512 = "//oorEZjL6sbPcKUaCdIGlIUeH26mgzimjBB77G6XRgnDl/L5wOnpyBGRe/Mmf5CVW3PwEBE1NjiMZ/ssFh4wA==";
      };
    };
    "@types/prop-types-15.7.5" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.5.tgz";
        sha512 = "JCB8C6SnDoQf0cNycqd/35A7MjcnK+ZTqE7judS6o7utxUCg6imJg3QK2qzHKszlTjcj2cn+NwMB2i96ubpj7w==";
      };
    };
    "@types/react-18.0.26" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "18.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-18.0.26.tgz";
        sha512 = "hCR3PJQsAIXyxhTNSiDFY//LhnMZWpNNr5etoCqx/iUfGc5gXWtQR2Phl908jVR6uPXacojQWTg4qRpkxTuGug==";
      };
    };
    "@types/react-is-17.0.3" = {
      name = "_at_types_slash_react-is";
      packageName = "@types/react-is";
      version = "17.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-is/-/react-is-17.0.3.tgz";
        sha512 = "aBTIWg1emtu95bLTLx0cpkxwGW3ueZv71nE2YFBpL8k/z5czEW8yYpOo8Dp+UUAFAtKwNaOsh/ioSeQnWlZcfw==";
      };
    };
    "@types/react-router-5.1.19" = {
      name = "_at_types_slash_react-router";
      packageName = "@types/react-router";
      version = "5.1.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-router/-/react-router-5.1.19.tgz";
        sha512 = "Fv/5kb2STAEMT3wHzdKQK2z8xKq38EDIGVrutYLmQVVLe+4orDFquU52hQrULnEHinMKv9FSA6lf9+uNT1ITtA==";
      };
    };
    "@types/react-transition-group-4.4.5" = {
      name = "_at_types_slash_react-transition-group";
      packageName = "@types/react-transition-group";
      version = "4.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-transition-group/-/react-transition-group-4.4.5.tgz";
        sha512 = "juKD/eiSM3/xZYzjuzH6ZwpP+/lejltmiS3QEzV/vmb/Q8+HfDmxu+Baga8UEMGBqV88Nbg4l2hY/K2DkyaLLA==";
      };
    };
    "@types/scheduler-0.16.2" = {
      name = "_at_types_slash_scheduler";
      packageName = "@types/scheduler";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.2.tgz";
        sha512 = "hppQEBDmlwhFAXKJX2KnWLYu5yMfi91yazPb2l+lbJiwW+wdo1gNeRA+3RgNSO39WYX2euey41KEwnqesU2Jew==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "aria-hidden-1.2.2" = {
      name = "aria-hidden";
      packageName = "aria-hidden";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-hidden/-/aria-hidden-1.2.2.tgz";
        sha512 = "6y/ogyDTk/7YAe91T3E2PR1ALVKyM2QbTio5HwM+N1Q6CMlCKhvClyIjkckBswa0f2xJhjsfzIGa1yVSe1UMVA==";
      };
    };
    "babel-plugin-macros-3.1.0" = {
      name = "babel-plugin-macros";
      packageName = "babel-plugin-macros";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-macros/-/babel-plugin-macros-3.1.0.tgz";
        sha512 = "Cg7TFGpIr01vOQNODXOOaGz2NpCU5gl8x1qJFbb6hbZxR7XrcE2vtbAsTAbJ7/xwJtUuJEw8K8Zr/AE0LHlesg==";
      };
    };
    "base64url-3.0.1" = {
      name = "base64url";
      packageName = "base64url";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64url/-/base64url-3.0.1.tgz";
        sha512 = "ir1UPr3dkwexU7FdV8qBBbNDRUhMmIekYMFZfi+C/sLNnRESKPl23nB9b2pltqfOQNnGzsDdId90AEtG5tCx4A==";
      };
    };
    "binary-extensions-2.2.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.2.0.tgz";
        sha512 = "jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browserslist-4.21.4" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.21.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.21.4.tgz";
        sha512 = "CBHJJdDmgjl3daYjN5Cp5kbTf1mUhZoS+beLklHIvkOWscs83YAhLlF3Wsh/lciQYAcbBJgTOD44VtG31ZM4Hw==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "caniuse-lite-1.0.30001439" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001439";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001439.tgz";
        sha512 = "1MgUzEkoMO6gKfXflStpYgZDlFM7M/ck/bgfVCACO5vnAf0fXoNVHdWtqGU+MYca+4bL9Z5bpOVmR33cWW9G2A==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chokidar-3.5.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.5.3.tgz";
        sha512 = "Dr3sfKRP6oTcjf2JmUmFJfeVMvXBdegxB0iVQ5eb2V10uFJUCAS8OByZdVAyVb8xXNz3GjjTgj9kLWsZTqE6kw==";
      };
    };
    "classnames-2.3.2" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.3.2.tgz";
        sha512 = "CSbhY4cFEJRe6/GQzIk5qXZ4Jeg5pcsP7b5peFSDpffpe1cqjASH/n9UTjBwOp6XpMSTwQ8Za2K5V02ueA7Tmw==";
      };
    };
    "clsx-1.2.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-1.2.1.tgz";
        sha512 = "EcR6r5a8bj6pu3ycsa/E/cKVGuTgZJZdsyUYHOksG/UHIiKfjxzRxYJpyVBwYaQeOvghal9fcc4PidlgzugAQg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "compute-scroll-into-view-1.0.20" = {
      name = "compute-scroll-into-view";
      packageName = "compute-scroll-into-view";
      version = "1.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/compute-scroll-into-view/-/compute-scroll-into-view-1.0.20.tgz";
        sha512 = "UCB0ioiyj8CRjtrvaceBLqqhZCVP+1B8+NWQhmdsm0VXOJtobBCf1dBQmebCCo34qZmUwZfIH2MZLqNHazrfjg==";
      };
    };
    "convert-source-map-1.9.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.9.0.tgz";
        sha512 = "ASFBup0Mz1uyiIjANan1jzLQami9z1PoYSZCiiYW2FczPbenXc45FZdBZLzOT+r6+iciuEModtmCti+hjaAk0A==";
      };
    };
    "cosmiconfig-7.1.0" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-7.1.0.tgz";
        sha512 = "AdmX6xUzdNASswsFtmwSt7Vj8po9IuqXm0UXz7QKPuEUmPB4XyjGfaAr2PSuELMwkRMVH1EpIkX5bTZGRB3eCA==";
      };
    };
    "csstype-3.1.1" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.1.tgz";
        sha512 = "DJR/VvkAvSZW9bTouZue2sSxDwdTN92uHjqeKVm+0dAqdfNykRzQ95tay8aXMBAAPpUiq4Qcug2L7neoRh2Egw==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "deepmerge-4.2.2" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.2.2.tgz";
        sha512 = "FJ3UgI4gIl+PHZm53knsuSFpE+nESMr7M4v9QcgB7S63Kj/6WqMiFQJpBBYz1Pt+66bZpP3Q7Lye0Oo9MPKEdg==";
      };
    };
    "dom-helpers-5.2.1" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-5.2.1.tgz";
        sha512 = "nRCa7CK3VTrM2NmGkIy4cbK7IZlgBE/PYMn55rrXefr5xXDP0LdtfPnblFDoVdcAfslJ7or6iqAUnx0CCGIWQA==";
      };
    };
    "downshift-6.1.12" = {
      name = "downshift";
      packageName = "downshift";
      version = "6.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/downshift/-/downshift-6.1.12.tgz";
        sha512 = "7XB/iaSJVS4T8wGFT3WRXmSF1UlBHAA40DshZtkrIscIN+VC+Lh363skLxFTvJwtNgHxAMDGEHT4xsyQFWL+UA==";
      };
    };
    "electron-to-chromium-1.4.284" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.284";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.284.tgz";
        sha512 = "M8WEXFuKXMYMVr45fo8mq0wUrrJHheiKZf6BArTKk9ZBYCKJEOU5H8cdWgDT+qCVZf7Na4lVUaZsA+h6uA9+PA==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "find-root-1.1.0" = {
      name = "find-root";
      packageName = "find-root";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-root/-/find-root-1.1.0.tgz";
        sha512 = "NKfW6bec6GfKc0SGx1e07QZY9PE99u0Bft/0rzSD5k3sO/vwkVUpDUKVm5Gpp5Ue3YfShPFTX2070tDs5kB9Ng==";
      };
    };
    "framer-motion-6.5.1" = {
      name = "framer-motion";
      packageName = "framer-motion";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/framer-motion/-/framer-motion-6.5.1.tgz";
        sha512 = "o1BGqqposwi7cgDrtg0dNONhkmPsUFDaLcKXigzuTFC5x58mE8iyTazxSudFzmT6MEyJKfjjU8ItoMe3W+3fiw==";
      };
    };
    "framesync-6.0.1" = {
      name = "framesync";
      packageName = "framesync";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/framesync/-/framesync-6.0.1.tgz";
        sha512 = "fUY88kXvGiIItgNC7wcTOl0SNRCVXMKSWW2Yzfmn7EKNc+MpCzcz9DhdHcdjbrtN3c6R4H5dTY2jiCpPdysEjA==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globals-11.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.12.0.tgz";
        sha512 = "WOBp/EEGUiIsJSp7wcv/y6MO+lV9UoncWqxuFfm8eBwzWNgyfBd6Gz+IeKQ9jCmyhoH99g15M3T+QaVHFjizVA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "hey-listen-1.0.8" = {
      name = "hey-listen";
      packageName = "hey-listen";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/hey-listen/-/hey-listen-1.0.8.tgz";
        sha512 = "COpmrF2NOg4TBWUJ5UVyaCU2A88wEMkUPK4hNqyCkqHbxT92BbvfjoSozkAIIm6XhicGlJHhFdullInrdhwU8Q==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "i-0.3.7" = {
      name = "i";
      packageName = "i";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/i/-/i-0.3.7.tgz";
        sha512 = "FYz4wlXgkQwIPqhzC5TdNMLSE5+GS1IIDJZY/1ZiEPCT2S3COUVZeT5OW4BmW4r5LHLQuOosSwsvnroG9GR59Q==";
      };
    };
    "immutable-4.1.0" = {
      name = "immutable";
      packageName = "immutable";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-4.1.0.tgz";
        sha512 = "oNkuqVTA8jqG1Q6c+UglTOD1xhC1BtjKI7XkCXRkZHrN5m18/XsnUp8Q89GkQO/z+0WjonSvl0FLhDYftp46nQ==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha512 = "zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-core-module-2.11.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.11.0.tgz";
        sha512 = "RRjxlvLDkD1YJwDbroBHMb+cukurkDWNyHx7D3oNB5x9rb5ogcksMC5wHCadcXoo67gVr/+3GFySh3134zi6rw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "jotai-1.11.1" = {
      name = "jotai";
      packageName = "jotai";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jotai/-/jotai-1.11.1.tgz";
        sha512 = "pHpaZUdvIpcS12ryMCrwtvmT/IovZAbicfrlll/Rb9394rwhqKoDFsDs0kv4oWtBy/XHHNv7iSZnQFmntiQj+w==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-2.5.2" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-2.5.2.tgz";
        sha512 = "OYu7XEzjkCQ3C5Ps3QIZsQfNpqoJyZZA99wd9aWd05NCtC5pWOkShK2mkL6HXQR6/Cy2lbNdPlZBpuQHXE63gA==";
      };
    };
    "json-parse-even-better-errors-2.3.1" = {
      name = "json-parse-even-better-errors";
      packageName = "json-parse-even-better-errors";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
        sha512 = "xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
      };
    };
    "json5-2.2.1" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.1.tgz";
        sha512 = "1hqLFMSrGHRHxav9q9gNjJ5EXznIxGVO09xQRrwplcS8qs28pZ8s8hupZAmqDwZUmVZ2Qb2jnyPOWcDH8m8dlA==";
      };
    };
    "lines-and-columns-1.2.4" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.2.4.tgz";
        sha512 = "7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "material-ripple-effects-2.0.1" = {
      name = "material-ripple-effects";
      packageName = "material-ripple-effects";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-ripple-effects/-/material-ripple-effects-2.0.1.tgz";
        sha512 = "hHlUkZAuXbP94lu02VgrPidbZ3hBtgXBtjlwR8APNqOIgDZMV8MCIcsclL8FmGJQHvnORyvoQgC965vPsiyXLQ==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "node-releases-2.0.6" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.6.tgz";
        sha512 = "PiVXnNuFm5+iYkLBNeq5211hvO38y63T0i2KKh2KnUs3RpzJ+JtODFjkD8yjLwnDkTYF1eKXheUwdssR+NRZdg==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "oauth-0.9.15" = {
      name = "oauth";
      packageName = "oauth";
      version = "0.9.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth/-/oauth-0.9.15.tgz";
        sha512 = "a5ERWK1kh38ExDEfoO6qUHJb32rd7aYmPHuyCu3Fta/cnICvYmgd2uhuKXvPD+PXB+gCEYYEaQdIRAjCOwAKNA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "parse-json-5.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-5.2.0.tgz";
        sha512 = "ayCKvm/phCGxOkYRSCM82iDwct8/EonSEgCSxWxD7ve6jHggsFl4fZVQBPRNgQoKiuV/odhFrGzQXZwbifC8Rg==";
      };
    };
    "passport-42-1.2.6" = {
      name = "passport-42";
      packageName = "passport-42";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport-42/-/passport-42-1.2.6.tgz";
        sha512 = "a1SraWSwH33NqRDe9ScG4MQwfj7RRBYLFtrJySn4tU4Ou7+caLxj6VQgaL4i+eZoKC6QAooL1Nqevn/W8vLXuQ==";
      };
    };
    "passport-oauth2-1.6.1" = {
      name = "passport-oauth2";
      packageName = "passport-oauth2";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport-oauth2/-/passport-oauth2-1.6.1.tgz";
        sha512 = "ZbV43Hq9d/SBSYQ22GOiglFsjsD1YY/qdiptA+8ej+9C1dL1TVB+mBE5kDH/D4AJo50+2i8f4bx0vg4/yDDZCQ==";
      };
    };
    "passport-strategy-1.0.0" = {
      name = "passport-strategy";
      packageName = "passport-strategy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport-strategy/-/passport-strategy-1.0.0.tgz";
        sha512 = "CB97UUvDKJde2V0KDWWB3lyf6PC3FaZP7YxZ2G8OAtn9p4HI9j9JLP9qjOGZFvyl8uwNT8qM+hGnz/n16NI7oA==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "path-type-4.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
        sha512 = "gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "popmotion-11.0.3" = {
      name = "popmotion";
      packageName = "popmotion";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/popmotion/-/popmotion-11.0.3.tgz";
        sha512 = "Y55FLdj3UxkR7Vl3s7Qr4e9m0onSnP8W7d/xQLsoJM40vs6UKHFdygs6SWryasTZYqugMjm3BepCF4CWXDiHgA==";
      };
    };
    "prop-types-15.8.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
        sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
      };
    };
    "react-18.2.0" = {
      name = "react";
      packageName = "react";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz";
        sha512 = "/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==";
      };
    };
    "react-dom-18.2.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz";
        sha512 = "6IMTriUmvsjHUjNtEDudZfuDQUoWXVxKHhlEGSk81n4YFS+r/Kl99wXiwlVXtPBtJenozv2P+hxDsw9eA7Xo6g==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-is-17.0.2" = {
      name = "react-is";
      packageName = "react-is";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-17.0.2.tgz";
        sha512 = "w2GsyukL62IJnlaff/nRegPQR94C/XXamvMWmSHRJ4y7Ts/4ocGRmTHvOs8PSE6pB3dWOrD/nueuU5sduBsQ4w==";
      };
    };
    "react-is-18.2.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-18.2.0.tgz";
        sha512 = "xWGDIW6x921xtzPkhiULtthJHoJvBbF3q26fzloPCK0hsvxtPVelvftw3zjbHWSkR2km9Z+4uxbDDK/6Zw9B8w==";
      };
    };
    "react-merge-refs-1.1.0" = {
      name = "react-merge-refs";
      packageName = "react-merge-refs";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-merge-refs/-/react-merge-refs-1.1.0.tgz";
        sha512 = "alTKsjEL0dKH/ru1Iyn7vliS2QRcBp9zZPGoWxUOvRGWPUYgjo+V01is7p04It6KhgrzhJGnIj9GgX8W4bZoCQ==";
      };
    };
    "react-responsive-canvas-1.0.2" = {
      name = "react-responsive-canvas";
      packageName = "react-responsive-canvas";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-responsive-canvas/-/react-responsive-canvas-1.0.2.tgz";
        sha512 = "r1cV0LPsxlMDdeJ53u0obUIxFPKCCD7/T3XJ/5wj0XmJi/u3qO27h0RZ3uZowSgVg+bilEKosDKxVtEr76v/JA==";
      };
    };
    "react-router-6.4.5" = {
      name = "react-router";
      packageName = "react-router";
      version = "6.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-6.4.5.tgz";
        sha512 = "1RQJ8bM70YEumHIlNUYc6mFfUDoWa5EgPDenK/fq0bxD8DYpQUi/S6Zoft+9DBrh2xmtg92N5HMAJgGWDhKJ5Q==";
      };
    };
    "react-transition-group-4.4.5" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "4.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-4.4.5.tgz";
        sha512 = "pZcd1MCJoiKiBR2NRxeCRg13uCXbydPnmB4EOeRrY7480qNWO8IIgQG6zlDkm6uRMsURXPuKq0GWtiM59a5Q6g==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "regenerator-runtime-0.13.11" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz";
        sha512 = "kY1AZVr2Ra+t+piVaJ4gxaFaReZVH40AKNo7UCX6W+dEwBo/2oZJzqfuN1qLq1oL45o56cPaTXELwrTh8Fpggg==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "sass-1.56.2" = {
      name = "sass";
      packageName = "sass";
      version = "1.56.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.56.2.tgz";
        sha512 = "ciEJhnyCRwzlBCB+h5cCPM6ie/6f8HrhZMQOf5vlU60Y1bI1rx5Zb0vlDZvaycHsg/MqFfF1Eq2eokAa32iw8w==";
      };
    };
    "scheduler-0.23.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz";
        sha512 = "CtuThmgHNg7zIZWAXi3AsyIzA3n4xx7aNyjwC2VJldO2LMVDhFK+63xGqq6CsJH4rTAt6/M+N4GhZiDYPx9eUw==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha512 = "LbrmJOMUSdEVxIKvdcJzQC+nQhe8FUZQTXQy6+I75skNgn3OoQ0DZA8YnFa7gp8tqtL3KPf1kmo0R5DoApeSGQ==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "style-value-types-5.0.0" = {
      name = "style-value-types";
      packageName = "style-value-types";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-value-types/-/style-value-types-5.0.0.tgz";
        sha512 = "08yq36Ikn4kx4YU6RD7jWEv27v4V+PUsOGa4n/as8Et3CuODMJQ00ENeAVXAeydX4Z2j1XHZF1K2sX4mGl18fA==";
      };
    };
    "stylis-4.1.3" = {
      name = "stylis";
      packageName = "stylis";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-4.1.3.tgz";
        sha512 = "GP6WDNWf+o403jrEp9c5jibKavrtLW+/qYGhFxFrG8maXhwTBI7gLLhiBb0o7uFccWN+EOS9aMO6cGHWAO07OA==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "tailwind-merge-1.8.0" = {
      name = "tailwind-merge";
      packageName = "tailwind-merge";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tailwind-merge/-/tailwind-merge-1.8.0.tgz";
        sha512 = "tER/2SbYRdfPYg6m4pDWZSlbymLTmDi+dx4iCsJmgmz4UDGzgnVelOvBe3GNtGCw9Bmc4MiObfJJbKeVL+KnMQ==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha512 = "/OaKK0xYrs3DmxRYqL/yDc+FxFUVYhDlXMhRmv3z915w2HF1tnN1omB354j8VUGO/hbRzyD6Y3sA7v7GS/ceog==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tslib-2.4.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.1.tgz";
        sha512 = "tGyy4dAjRIEwI7BzsB0lynWgOpfqjUdq91XXAlIWD2OwKBH7oCl/GZG/HT4BOHrTlPMOASlMQ7veyTqpmRcrNA==";
      };
    };
    "uid2-0.0.4" = {
      name = "uid2";
      packageName = "uid2";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid2/-/uid2-0.0.4.tgz";
        sha512 = "IevTus0SbGwQzYh3+fRsAMTVVPOoIVufzacXcHPmdlle1jUpq7BRL+mw3dgeLanvGZdwwbWhRV6XrcFNdBmjWA==";
      };
    };
    "update-browserslist-db-1.0.10" = {
      name = "update-browserslist-db";
      packageName = "update-browserslist-db";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-browserslist-db/-/update-browserslist-db-1.0.10.tgz";
        sha512 = "OztqDenkfFkbSG+tRxBeAnCVPckDBcvibKd35yDONx6OU8N7sqgwc7rCbkJ/WcYtVRZ4ba68d6byhC21GFh7sQ==";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha512 = "pMZTvIkT1d+TFGvDOqodOclx0QWkkgi6Tdoa8gC8ffGAAqz9pzPTZWAybbsHHoED/ztMtkv/VoYTYyShUn81hA==";
      };
    };
    "yaml-1.10.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "1.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-1.10.2.tgz";
        sha512 = "r3vXyErRCYJ7wg28yvBY5VSoAF8ZvlcW9/BwUzEtUsjvX/DKs24dIkuwjtuprwJJHsbyUbLApepYTR1BN4uHrg==";
      };
    };
  };
  args = {
    name = "reactjs-vite-tailwindcss-boilerplate";
    packageName = "reactjs-vite-tailwindcss-boilerplate";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."@ampproject/remapping-2.2.0"
      sources."@babel/code-frame-7.18.6"
      sources."@babel/compat-data-7.20.5"
      sources."@babel/core-7.20.5"
      (sources."@babel/generator-7.20.5" // {
        dependencies = [
          sources."@jridgewell/gen-mapping-0.3.2"
        ];
      })
      sources."@babel/helper-compilation-targets-7.20.0"
      sources."@babel/helper-environment-visitor-7.18.9"
      sources."@babel/helper-function-name-7.19.0"
      sources."@babel/helper-hoist-variables-7.18.6"
      sources."@babel/helper-module-imports-7.18.6"
      sources."@babel/helper-module-transforms-7.20.2"
      sources."@babel/helper-plugin-utils-7.20.2"
      sources."@babel/helper-simple-access-7.20.2"
      sources."@babel/helper-split-export-declaration-7.18.6"
      sources."@babel/helper-string-parser-7.19.4"
      sources."@babel/helper-validator-identifier-7.19.1"
      sources."@babel/helper-validator-option-7.18.6"
      sources."@babel/helpers-7.20.6"
      sources."@babel/highlight-7.18.6"
      sources."@babel/parser-7.20.5"
      sources."@babel/plugin-syntax-jsx-7.18.6"
      sources."@babel/runtime-7.20.6"
      sources."@babel/template-7.18.10"
      sources."@babel/traverse-7.20.5"
      sources."@babel/types-7.20.5"
      sources."@emotion/babel-plugin-11.10.5"
      sources."@emotion/cache-11.10.5"
      sources."@emotion/hash-0.9.0"
      sources."@emotion/is-prop-valid-1.2.0"
      sources."@emotion/memoize-0.8.0"
      sources."@emotion/react-11.10.5"
      sources."@emotion/serialize-1.1.1"
      sources."@emotion/sheet-1.2.1"
      sources."@emotion/styled-11.10.5"
      sources."@emotion/unitless-0.8.0"
      sources."@emotion/use-insertion-effect-with-fallbacks-1.0.0"
      sources."@emotion/utils-1.2.0"
      sources."@emotion/weak-memoize-0.3.0"
      sources."@floating-ui/core-1.0.4"
      sources."@floating-ui/dom-1.0.9"
      sources."@floating-ui/react-dom-1.0.1"
      sources."@floating-ui/react-dom-interactions-0.8.1"
      sources."@jridgewell/gen-mapping-0.1.1"
      sources."@jridgewell/resolve-uri-3.1.0"
      sources."@jridgewell/set-array-1.1.2"
      sources."@jridgewell/sourcemap-codec-1.4.14"
      sources."@jridgewell/trace-mapping-0.3.17"
      sources."@material-tailwind/react-1.2.4"
      sources."@motionone/animation-10.15.1"
      sources."@motionone/dom-10.12.0"
      sources."@motionone/easing-10.15.1"
      sources."@motionone/generators-10.15.1"
      sources."@motionone/types-10.15.1"
      sources."@motionone/utils-10.15.1"
      (sources."@mui/base-5.0.0-alpha.107" // {
        dependencies = [
          sources."react-is-18.2.0"
        ];
      })
      sources."@mui/core-downloads-tracker-5.10.17"
      sources."@mui/icons-material-5.10.16"
      (sources."@mui/lab-5.0.0-alpha.109" // {
        dependencies = [
          sources."react-is-18.2.0"
        ];
      })
      (sources."@mui/material-5.10.17" // {
        dependencies = [
          sources."@mui/base-5.0.0-alpha.109"
          sources."react-is-18.2.0"
        ];
      })
      sources."@mui/private-theming-5.10.16"
      sources."@mui/styled-engine-5.10.16"
      sources."@mui/system-5.10.17"
      sources."@mui/types-7.2.2"
      (sources."@mui/utils-5.10.16" // {
        dependencies = [
          sources."react-is-18.2.0"
        ];
      })
      sources."@popperjs/core-2.11.6"
      sources."@remix-run/router-1.0.5"
      sources."@types/history-4.7.11"
      sources."@types/parse-json-4.0.0"
      sources."@types/prop-types-15.7.5"
      sources."@types/react-18.0.26"
      sources."@types/react-is-17.0.3"
      sources."@types/react-router-5.1.19"
      sources."@types/react-transition-group-4.4.5"
      sources."@types/scheduler-0.16.2"
      sources."ansi-styles-3.2.1"
      sources."anymatch-3.1.3"
      sources."aria-hidden-1.2.2"
      sources."babel-plugin-macros-3.1.0"
      sources."base64url-3.0.1"
      sources."binary-extensions-2.2.0"
      sources."braces-3.0.2"
      sources."browserslist-4.21.4"
      sources."callsites-3.1.0"
      sources."caniuse-lite-1.0.30001439"
      (sources."chalk-2.4.2" // {
        dependencies = [
          sources."escape-string-regexp-1.0.5"
        ];
      })
      sources."chokidar-3.5.3"
      sources."classnames-2.3.2"
      sources."clsx-1.2.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."compute-scroll-into-view-1.0.20"
      sources."convert-source-map-1.9.0"
      sources."cosmiconfig-7.1.0"
      sources."csstype-3.1.1"
      sources."debug-4.3.4"
      sources."deepmerge-4.2.2"
      sources."dom-helpers-5.2.1"
      (sources."downshift-6.1.12" // {
        dependencies = [
          sources."react-is-17.0.2"
        ];
      })
      sources."electron-to-chromium-1.4.284"
      sources."error-ex-1.3.2"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-4.0.0"
      sources."fill-range-7.0.1"
      sources."find-root-1.1.0"
      (sources."framer-motion-6.5.1" // {
        dependencies = [
          sources."@emotion/is-prop-valid-0.8.8"
          sources."@emotion/memoize-0.7.4"
        ];
      })
      sources."framesync-6.0.1"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."gensync-1.0.0-beta.2"
      sources."glob-parent-5.1.2"
      sources."globals-11.12.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."hey-listen-1.0.8"
      sources."hoist-non-react-statics-3.3.2"
      sources."i-0.3.7"
      sources."immutable-4.1.0"
      sources."import-fresh-3.3.0"
      sources."is-arrayish-0.2.1"
      sources."is-binary-path-2.1.0"
      sources."is-core-module-2.11.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."jotai-1.11.1"
      sources."js-tokens-4.0.0"
      sources."jsesc-2.5.2"
      sources."json-parse-even-better-errors-2.3.1"
      sources."json5-2.2.1"
      sources."lines-and-columns-1.2.4"
      sources."loose-envify-1.4.0"
      sources."material-ripple-effects-2.0.1"
      sources."ms-2.1.2"
      sources."node-releases-2.0.6"
      sources."normalize-path-3.0.0"
      sources."oauth-0.9.15"
      sources."object-assign-4.1.1"
      sources."parent-module-1.0.1"
      sources."parse-json-5.2.0"
      sources."passport-42-1.2.6"
      sources."passport-oauth2-1.6.1"
      sources."passport-strategy-1.0.0"
      sources."path-parse-1.0.7"
      sources."path-type-4.0.0"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.1"
      sources."popmotion-11.0.3"
      sources."prop-types-15.8.1"
      sources."react-18.2.0"
      sources."react-dom-18.2.0"
      sources."react-is-16.13.1"
      sources."react-merge-refs-1.1.0"
      sources."react-responsive-canvas-1.0.2"
      sources."react-router-6.4.5"
      sources."react-transition-group-4.4.5"
      sources."readdirp-3.6.0"
      sources."regenerator-runtime-0.13.11"
      sources."resolve-1.22.1"
      sources."resolve-from-4.0.0"
      sources."sass-1.56.2"
      sources."scheduler-0.23.0"
      sources."semver-6.3.0"
      sources."source-map-0.5.7"
      sources."source-map-js-1.0.2"
      sources."style-value-types-5.0.0"
      sources."stylis-4.1.3"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."tailwind-merge-1.8.0"
      sources."to-fast-properties-2.0.0"
      sources."to-regex-range-5.0.1"
      sources."tslib-2.4.1"
      sources."uid2-0.0.4"
      sources."update-browserslist-db-1.0.10"
      sources."utils-merge-1.0.1"
      sources."yaml-1.10.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "This is a React + vite boilerplate to be used with Tailwindcss.";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
